# Generated by Django 3.0.4 on 2020-10-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_email', models.EmailField(max_length=50)),
                ('cust_phone', models.IntegerField()),
                ('cust_address', models.TextField(max_length=100)),
                ('cust_gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Owner',
            fields=[
                ('own_id', models.IntegerField(primary_key=True, serialize=False)),
                ('own_name', models.CharField(max_length=50)),
                ('own_email', models.EmailField(max_length=50)),
                ('own_phone', models.IntegerField()),
                ('shop_name', models.CharField(max_length=50, unique=True)),
                ('shop_address', models.TextField(max_length=100, unique=True)),
                ('own_gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Barber',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=50)),
                ('emp_phone', models.IntegerField()),
                ('emp_gender', models.CharField(max_length=6)),
                ('shop_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_addresss', to='EasyBarber.Shop_Owner')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_Barbers', to='EasyBarber.Shop_Owner')),
            ],
        ),
    ]
