# Generated by Django 3.0.4 on 2020-12-02 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBarber', '0002_auto_20201130_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='cust_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='emp_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EasyBarber.Shop_Barber', to_field='emp_name'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EasyBarber.Shop_Owner', to_field='shop_name'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='app_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EasyBarber.Appointment'),
        ),
    ]
