# Generated by Django 3.0.4 on 2020-10-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBarber', '0002_auto_20201026_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_barber',
            name='shop_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='EasyBarber.Shop_Owner', to_field='shop_address'),
        ),
        migrations.AlterField(
            model_name='shop_barber',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='EasyBarber.Shop_Owner', to_field='shop_name'),
        ),
    ]
