# Generated by Django 3.0.4 on 2020-12-06 10:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBarber', '0003_auto_20201202_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='cust_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='review_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
