# Generated by Django 3.0.4 on 2020-10-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBarber', '0003_auto_20201027_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_no', models.IntegerField()),
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('service_type', models.CharField(choices=[('Shop', 'shop'), ('Home', 'home')], max_length=4)),
                ('service_category', models.CharField(choices=[('Haircut', 'haircut'), ('Massage', 'massage'), ('Hair Colour', 'hair colour'), ('Shave', 'shave'), ('Facial', 'facial')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shop_barber',
            name='emp_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')])),
                ('comment', models.TextField(max_length=300)),
                ('app_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EasyBarber.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('app_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EasyBarber.Appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='cust_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EasyBarber.Customer', to_field='cust_name'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='emp_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EasyBarber.Shop_Barber', to_field='emp_name'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EasyBarber.Shop_Owner', to_field='shop_name'),
        ),
    ]
