# Generated by Django 3.0.4 on 2020-12-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBarber', '0005_auto_20201206_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='emp_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EasyBarber.Shop_Barber', to_field='emp_name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EasyBarber.Shop_Owner', to_field='shop_name'),
        ),
    ]
