# Generated by Django 3.0.4 on 2020-12-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBarber', '0008_auto_20201208_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='emp_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EasyBarber.Shop_Barber', to_field='emp_name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EasyBarber.Shop_Owner', to_field='shop_name'),
        ),
        migrations.AlterField(
            model_name='shop_barber',
            name='shop_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='EasyBarber.Shop_Owner', to_field='shop_address'),
        ),
        migrations.AlterField(
            model_name='shop_barber',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='EasyBarber.Shop_Owner', to_field='shop_name'),
        ),
    ]
